(function(root,factory){if(typeof module==='object')module.exports=factory();else root.Jelly=factory();})(typeof window!=='undefined'?window:this,function(){
'use strict';
const colors=[['#82d9b1','#b7f3d5','#49ab89'],['#ad99ed','#ded2ff','#8266c7'],['#ffb48d','#ffdbc0','#e78d69'],['#88cce5','#c7edf9','#58a8c7'],['#f5a6c5','#ffdbec','#d97f9f'],['#e5d777','#fff1ad','#b9ac52']];
class Game{
 constructor(seed=917){this.seed=seed;this.reset();this.state='ready';}
 random(){this.seed=(Math.imul(1664525,this.seed)+1013904223)>>>0;return this.seed/4294967296;}
 reset(){this.time=0;this.blocks=[{x:130,w:220,y:650,color:0,stamp:-10}];this.moving={x:5,w:220,y:550,color:1};this.direction=1;this.speed=150;this.count=0;this.perfect=0;this.combo=0;this.particles=[];this.scraps=[];this.events=[];this.camera=0;this.drop=null;this.cooldown=0;this.flash=0;this.state='playing';this.lastResult='';}
 tap(){if(this.state!=='playing'||this.drop||this.cooldown>0)return false;this.drop={target:this.blocks.at(-1).y-43,vy:240};this.events.push({type:'tap',time:this.time});return true;}
 land(){const top=this.blocks.at(-1),m=this.moving,offset=m.x-top.x;let left=Math.max(m.x,top.x),right=Math.min(m.x+m.w,top.x+top.w),width=right-left;
  if(width<=0){this.scraps.push({...m,vx:offset>0?100:-100,vy:50,rot:0});this.state='over';this.lastResult='miss';this.events.push({type:'miss',time:this.time,count:this.count});this.drop=null;return;}
  if(Math.abs(offset)<=8){left=top.x;width=top.w;this.perfect++;this.combo++;this.lastResult=this.combo>=3?'combo':'perfect';}else{this.combo=0;this.lastResult='cut';const cut=offset>0?{x:right,w:m.x+m.w-right}:{x:m.x,w:left-m.x};if(cut.w>0)this.scraps.push({...m,...cut,vx:offset>0?95:-95,vy:20,rot:0});}
  this.count++;this.flash=.8;this.blocks.push({x:left,w:width,y:top.y-43,color:m.color,stamp:this.time});this.events.push({type:this.lastResult,time:this.time,count:this.count,width});
  if(this.lastResult!=='cut')for(let i=0;i<18;i++)this.particles.push({x:left+width/2,y:m.y,vx:(this.random()-.5)*230,vy:-this.random()*200-30,life:.9,color:colors[(i+this.count)%6][0]});this.drop=null;
  if(this.count>=12){this.state='won';this.lastResult='won';this.events.push({type:'won',time:this.time,count:this.count});for(let i=0;i<60;i++)this.particles.push({x:240,y:this.blocks.at(-1).y-70,vx:(this.random()-.5)*430,vy:-this.random()*400,life:2,color:colors[i%6][0]});return;}
  this.direction=this.count%2?-1:1;this.moving={x:this.direction>0?-width:480,w:width,y:this.blocks.at(-1).y-100,color:(this.count+1)%6};this.speed=Math.min(265,150+this.count*9);this.cooldown=.23;
 }
 update(dt){if(this.state==='paused')return;dt=Math.min(dt,.034);this.time+=dt;this.flash=Math.max(0,this.flash-dt);this.camera+=(Math.max(0,410-this.blocks.at(-1).y)-this.camera)*Math.min(1,dt*5);
 if(this.state==='playing'){if(this.drop){this.drop.vy+=2200*dt;this.moving.y+=this.drop.vy*dt;if(this.moving.y>=this.drop.target){this.moving.y=this.drop.target;this.land();}}else if(this.cooldown>0)this.cooldown-=dt;else{this.moving.x+=this.direction*this.speed*dt;if(this.direction>0&&this.moving.x>475-this.moving.w){this.moving.x=475-this.moving.w;this.direction=-1;}else if(this.direction<0&&this.moving.x<5){this.moving.x=5;this.direction=1;}}}
 this.scraps.forEach(s=>{s.x+=s.vx*dt;s.y+=s.vy*dt;s.vy+=1100*dt;s.rot+=dt*s.vx*.006;});this.scraps=this.scraps.filter(s=>s.y+this.camera<1100);this.particles.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=450*dt;p.life-=dt;});this.particles=this.particles.filter(p=>p.life>0);
 }
 pause(){if(this.state==='playing'){this.state='paused';return true;}return false;}resume(){if(this.state==='paused')this.state='playing';}
}
function round(c,x,y,w,h,r){c.beginPath();c.roundRect(x,y,w,h,r);}
function jelly(c,b,t,cam,face=true,still=false){const col=colors[b.color%6],age=t-(b.stamp??-10),impact=still?0:Math.exp(-age*5)*Math.sin(age*24)*.17,idle=still?0:Math.sin(t*2.2+b.color)*.012,h=43*(1-impact),w=b.w*(1+impact*.16),x=b.x+(b.w-w)/2,y=b.y+cam+43-h;
c.save();c.translate(x+w/2,y+h);c.rotate((b.rot||0)+idle);c.translate(-w/2,-h);c.shadowColor='#57334818';c.shadowBlur=9;c.shadowOffsetY=5;const grad=c.createLinearGradient(0,0,0,h);grad.addColorStop(0,col[0]);grad.addColorStop(1,col[2]);c.fillStyle=grad;round(c,0,0,w,h,Math.min(11,w/4));c.fill();c.shadowBlur=0;c.shadowOffsetY=0;c.fillStyle=col[1];round(c,1,0,Math.max(0,w-2),14,Math.min(9,w/4));c.fill();c.fillStyle='#ffffff75';round(c,Math.min(7,w/5),17,Math.min(9,w*.09),Math.max(5,h-24),2);c.fill();c.strokeStyle='#ffffff66';c.lineWidth=1;round(c,.5,.5,Math.max(0,w-1),h-1,Math.min(11,w/4));c.stroke();
if(face&&w>42){const gap=Math.min(18,w*.14);c.fillStyle='#40324d';c.beginPath();c.ellipse(w/2-gap,27,2.8,3.7,0,0,Math.PI*2);c.ellipse(w/2+gap,27,2.8,3.7,0,0,Math.PI*2);c.fill();c.strokeStyle='#40324d';c.lineWidth=1.8;c.beginPath();c.arc(w/2,29,4.5,0,Math.PI);c.stroke();c.fillStyle='#ed78976b';c.beginPath();c.ellipse(w/2-gap-7,32,4,2,0,0,Math.PI*2);c.ellipse(w/2+gap+7,32,4,2,0,0,Math.PI*2);c.fill();}c.restore();}
function render(c,g,w,h,options={}){const scale=Math.min(w/480,h/800),ox=(w-480*scale)/2,oy=(h-800*scale)/2;c.fillStyle='#fcf6eb';c.fillRect(0,0,w,h);c.save();c.translate(ox,oy);c.scale(scale,scale);const bg=c.createLinearGradient(0,0,0,800);bg.addColorStop(0,'#fcf6eb');bg.addColorStop(.6,'#f9ede3');bg.addColorStop(1,'#f2dfd8');c.fillStyle=bg;c.fillRect(0,0,480,800);
c.fillStyle='#e9dbd555';c.beginPath();c.ellipse(70,790+g.camera*.1,330,155,0,0,Math.PI*2);c.fill();c.fillStyle='#e0dbcf55';c.beginPath();c.ellipse(480,800+g.camera*.1,320,165,0,0,Math.PI*2);c.fill();c.strokeStyle='#aa8e8120';c.lineWidth=1;for(let i=0;i<13;i++){const y=735-i*55+(g.camera*.2)%55;c.beginPath();c.moveTo(30,y);c.lineTo(39,y);c.moveTo(441,y);c.lineTo(450,y);c.stroke();}const ground=696+g.camera-(g.state==='ready'?110:0);c.fillStyle='#987d6f15';c.beginPath();c.ellipse(240,ground+22,156,17,0,0,Math.PI*2);c.fill();c.fillStyle='#d4b9a2';round(c,91,ground-3,298,18,9);c.fill();c.fillStyle='#fffaf2';round(c,83,ground-12,314,17,9);c.fill();const cam=g.camera;
if(g.state==='ready'){for(let i=0;i<5;i++)jelly(c,{x:130+i*4,w:220-i*8,y:650-i*43,color:i,stamp:-10},g.time,-110,true,options.still);jelly(c,{x:130+Math.sin(g.time*1.4)*105,w:188,y:375,color:5,stamp:-10},g.time,0,true,options.still);c.setLineDash([4,6]);c.strokeStyle='#b2a1b077';c.beginPath();c.moveTo(148,312);c.lineTo(148,362);c.moveTo(336,312);c.lineTo(336,362);c.stroke();c.setLineDash([]);}else{const top=g.blocks.at(-1);if(g.state==='playing'&&!g.drop){c.fillStyle='#ad99ed12';c.fillRect(top.x,top.y-110+cam,top.w,108);c.setLineDash([3,5]);c.strokeStyle='#a995b150';c.beginPath();c.moveTo(top.x,top.y-110+cam);c.lineTo(top.x,top.y+cam);c.moveTo(top.x+top.w,top.y-110+cam);c.lineTo(top.x+top.w,top.y+cam);c.stroke();c.setLineDash([]);}g.blocks.forEach(b=>jelly(c,b,g.time,cam,true,options.still));g.scraps.forEach(b=>jelly(c,b,g.time,cam,false,options.still));if(g.state==='playing'||g.state==='paused')jelly(c,g.moving,g.time,cam,true,options.still);}
if(!options.still)g.particles.forEach(p=>{c.globalAlpha=Math.min(1,p.life*2);c.fillStyle=p.color;c.save();c.translate(p.x,p.y+cam);c.rotate(p.life*3);c.fillRect(-3,-3,6,6);c.restore();});c.globalAlpha=1;if(g.flash>0&&g.lastResult!=='cut'&&g.lastResult!=='won'){c.globalAlpha=Math.min(1,g.flash*3);c.fillStyle='#5c4776';c.textAlign='center';c.font='900 26px sans-serif';c.fillText(g.lastResult==='combo'?'PERFECT × '+g.combo:'PERFECT!',240,g.blocks.at(-1).y+cam-80);c.globalAlpha=1;}c.restore();}
return{Game,render,colors};});
