const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),{once}=require('events');
const {createCanvas,GlobalFonts}=require('C:/Users/ayura/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/@napi-rs/canvas');
const {Game,render}=require('../experiments/jelly-bridge/engine.js');const out=path.resolve(process.argv[2]);fs.mkdirSync(out,{recursive:true});const ffmpeg=process.argv[3];GlobalFonts.registerFromPath('C:/Windows/Fonts/arialbd.ttf','Campaign');
const g=new Game();g.reset();const taps=[],fractions=[.5,.18,.82,.5,.25,.5];let finish=null;
for(let n=0;n<60*40;n++){if(g.state==='waiting'){g.tap();taps.push(g.time);}else if(g.state==='growing'&&g.length>=g.next.x+g.next.w*fractions[g.count]-g.current.x-g.current.w){g.tap();taps.push(g.time);}g.update(1/60);if(g.state==='won'&&finish===null)finish=g.time+1.5;if(finish&&g.time>=finish)break;}
if(g.state!=='won')throw Error('Input replay did not finish');const frames=Math.ceil(g.time*30),duration=frames/30,events=g.events;fs.writeFileSync(path.join(out,'replay.json'),JSON.stringify({taps,events,duration,provenance:'Scripted input replay, identical engine and speed, not a human record.'},null,2));
const rate=48000,count=Math.ceil(duration*rate),wav=Buffer.alloc(44+count*2);wav.write('RIFF');wav.writeUInt32LE(36+count*2,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(count*2,40);
for(const e of events){const f=({grow:300,drop:220,land:530,perfect:760,won:880})[e.type]||440;for(let j=0;j<rate*.18;j++){const i=Math.floor(e.time*rate)+j;if(i>=count)break;const v=Math.sin(2*Math.PI*f*j/rate)*Math.exp(-j/rate*25)*.16;wav.writeInt16LE(Math.round(v*32767),44+i*2);}}fs.writeFileSync(path.join(out,'pops.wav'),wav);
const W=1080,H=1920,c=createCanvas(W,H),ctx=c.getContext('2d'),scene=createCanvas(480,720),sc=scene.getContext('2d');
const proc=spawn(ffmpeg,['-y','-f','rawvideo','-pix_fmt','rgba','-s','1080x1920','-r','30','-i','pipe:0','-i',path.join(out,'pops.wav'),'-c:v','libx264','-preset','fast','-crf','20','-pix_fmt','yuv420p','-c:a','aac','-b:a','128k','-movflags','+faststart','-shortest',path.join(out,'jelly-bridge-004.mp4')],{stdio:['pipe','ignore','pipe'],windowsHide:true});let err='';proc.stderr.on('data',b=>err=(err+b).slice(-4000));proc.on('error',e=>{console.error(e.message);process.exitCode=1;});proc.stdin.on('error',()=>{});
function label(t,y,size,color='#4c3b60'){ctx.fillStyle=color;ctx.font='bold '+size+'px Campaign';ctx.textAlign='center';ctx.fillText(t,540,y);}
(async()=>{g.reset();let next=0;for(let frame=0;frame<frames;frame++){for(let sub=0;sub<2;sub++){if(next<taps.length&&g.time>=taps[next]-.00001){g.tap();next++;}g.update(1/60);}render(sc,g,480,720);ctx.fillStyle='#f9f3e9';ctx.fillRect(0,0,W,H);ctx.drawImage(scene,0,200,W,1620);label('CAN YOU BRIDGE THE GAP?',130,52);label('JELLY BRIDGE · K_games',185,25,'#9173b7');ctx.fillStyle='#f9f3e9f2';ctx.fillRect(0,1630,1080,290);label(g.state==='won'?'SIX ISLANDS. ONE LITTLE JELLY.':g.state==='growing'?'TAP TO STOP THE STRETCH.':'STRETCH. DROP. CROSS.',1710,40);label('Free browser game · Tiny Play Lab 004',1780,27,'#846b95');label('mrbeside.github.io/orbit-flip/experiments/jelly-bridge',1850,23,'#846b95');if([0,Math.floor(frames/2),frames-10].includes(frame))fs.writeFileSync(path.join(out,'qa-'+frame+'.png'),c.toBuffer('image/png'));if(!proc.stdin.write(Buffer.from(ctx.getImageData(0,0,W,H).data)))await once(proc.stdin,'drain');if(frame%180===0)console.log('Rendered '+frame+'/'+frames);}proc.stdin.end();const [code]=await once(proc,'close');if(code)throw Error(err);console.log(JSON.stringify({duration,count:g.count,state:g.state,frames}));})().catch(e=>{console.error(e);proc.kill();process.exitCode=1;});
